import { Link } from 'react-router-dom'
import './index.scss'
import LogoTitle from '../../assets/images/logo_a.png'
import letterClass from '../AnimatedLetters/index.js'
import { useState } from 'react'
import AnimatedLetters from '../AnimatedLetters/index.js'

const Home = () => {
    const [letterClass, setLetterClass] = useState('text-animate')
    const nameArray = [
        'H',
        'e',
        'y',
        ',',
        'T',
        'h',
        'i',
        's',
        'i',
        's',
        'd',
        'i',
        't',
        'y',
        'a',
    ]
    const jobArray = [
        'I',
        'a',
        'm',
        'a',
        'C',
        'o',
        'm',
        'p',
        'u',
        't',
        'e',
        'r',
        'S',
        'c',
        'i',
        'e',
        'n',
        'c',
        'e',
        'a',
        'n',
        'd',
        'E',
        'n',
        'g',
        'i',
        'n',
        'e',
        'e',
        'r',
        'i',
        'n',
        'g',
        's',
        't',
        'u',
        'd',
        'e',
        'n',
        't',
        'f',
        'r',
        'o',
        'm',
        'N',
        'o',
        'r',
        't',
        'h',
        'S',
        'o',
        'u',
        't',
        'h',
        'U',
        'n',
        'i',
        'v',
        'e',
        'r',
        's',
        'i',
        't',
        'y',
        'D',
        'h',
        'a',
        'k',
        'a',
        '.',
        'I',
        'w',
        'o',
        'r',
        'k',
        'w',
        'i',
        't',
        'h',
        'w',
        'e',
        'b',
        'a',
        'p',
        'p',
        'l',
        'i',
        'c',
        'a',
        't',
        'i',
        'o',
        'n',
        's',
        'a',
        'n',
        'd',
        'd',
        'e',
        'e',
        'p',
        'l',
        'e',
        'a',
        'r',
        'n',
        'i',
        'n',
        'g',
        'o',
        'r',
        'm',
        'a',
        'c',
        'h',
        'i',
        'n',
        'e',
        'l',
        'e',
        'a',
        'r',
        'n',
        'i',
        'n',
        'g',
        'a',
        'n',
        'd',
        'a',
        'l',
        's',
        'o',
        'I',
        'a',
        'm',
        'a',
        'L',
        'i',
        'n',
        'u',
        'x',
        'e',
        'n',
        't',
        'h',
        'u',
        's',
        'i',
        'a',
        's',
        't',
        '.',
        'C',
        'u',
        'r',
        'r',
        'e',
        'n',
        't',
        'l',
        'y',
        'I',
        'a',
        'm',
        'w',
        'o',
        'r',
        'k',
        'i',
        'n',
        'g',
        'o',
        'n',
        'm',
        'y',
        '"',
        'S',
        'e',
        'n',
        'i',
        'o',
        'r',
        'D',
        'e',
        's',
        'i',
        'g',
        'n',
        'P',
        'r',
        'o',
        'j',
        'e',
        'c',
        't',
        '"',
        'w',
        'h',
        'e',
        'r',
        'e',
        'I',
        'a',
        'm',
        'b',
        'a',
        's',
        'i',
        'c',
        'a',
        'l',
        'l',
        'y',
        'w',
        'o',
        'r',
        'k',
        'i',
        'n',
        'g',
        'w',
        'i',
        't',
        'h',
        'd',
        'e',
        'e',
        'p',
        'l',
        'e',
        'a',
        'r',
        'n',
        'i',
        'n',
        'g',
        'a',
        'n',
        'd',
        'o',
        'n',
        's',
        'o',
        'm',
        'e',
        'p',
        'e',
        't',
        'p',
        'r',
        'o',
        'j',
        'e',
        'c',
        't',
        's',
        'a',
        's',
        'w',
        'e',
        'l',
        'l',
        '.',
    ];

    return (
        <div className="container home-page">
            <div className="text-zone">
                <h1 className={ letterClass }>
                    Hey, <br />
                    This is <img src={LogoTitle} />
                    ditya
                </h1>
                <AnimatedLetters letterClass={letterClass}
                    strArray={nameArray}
                    idx = {15}
                />
                <br />
                <AnimatedLetters letterClass={letterClass}
                    strArray={jobArray}
                    idx = {616}
                />
                <br />
                <h2 className={letterClass}>
                    I am a Computer Science and Engineering student from North
                    South University, Dhaka. I work with web applications and
                    deep learning or machine learning and also I am a Linux
                    enthusiast. Currently I am working on my "Senior Design
                    Project" where I am basically working with deep learning and
                    on some pet projects as well.
                </h2>
                <Link to="/contact" className="flat-button">
                    Feel Free to Connect With Me
                </Link>
            </div>
        </div>
    )
}

export default Home
